### PR TITLE
Add a Travis CI config file

### PR DESCRIPTION
**Pull request by oalders**
I generated the file using https://metacpan.org/release/App-CISetup

Passing build results are at https://travis-ci.org/oalders/moosex-workers/builds/466597535

You'd just need to flip the switch at https://travis-ci.org/account/repositories to enable builds on this upstream repository. This was done as part of the last month of the CPAN Pull Request Challenge (CPC).

### CODE REVIEW

**Comment by rkitover** [comment]
@jhannah can you turn this on please?

**Comment by jhannah** [comment]
uhh... so when I click the link Travis CI appears to be requesting access to private Organizations that I can't grant any accesses to... can this repo move to someone's github account where everything is open source?

**Comment by rkitover** [comment]
I can probably turn it on without moving the repo by adding this one to my travis account. Should I?

**Comment by jhannah** [comment]
@rkitover ya, feel free. Sorry, I just can't risk exposing client info. :)

**Comment by rkitover** [comment]
@jhannah I think I need admin access to this repo to enable this, I don't see it in my list yet.

**Comment by jhannah** [comment]
@rkitover hmm... github is only letting me create "Collaborators" ... I don't see any way to give you a higher level of access to the repo

**Comment by rkitover** [comment]
Yeah I think an org is required for that, oh well.

**Pull request merged**
